/* -------------------------------------------------------------------------- */
/*                             Import Dependencies                            */
/* -------------------------------------------------------------------------- */

    const {Client} = require('../models')

/* -------------------------------------------------------------------------- */
/*                            Define Data to Inject                           */
/* -------------------------------------------------------------------------- */
    // Define array of data to seed
    const clientData = [
        {
            // client_id: generated by sequelize assumed 1
            company_id: 1,
            name: "AGCO",
            addrLine1: "AGCO Address Line 1",
            addrLine2: "AGCO Address Line 2",
            city:"Duluth",
            state:"Georgia",
            zipCode:30338,
            contactPerson: "AGCO Contact Person",
            contactPhoneNumber: "404-455-6778",
            contactEmail: "agco@agco.com"
        },
        {
            // client_id: generated by sequelize assumed 1
            company_id: 1,
            name: "Fiserv",
            addrLine1: "Fiserv Address Line 1",
            addrLine2: "Fiserv Address Line 2",
            city:"Alpharetta",
            state:"Georgia",
            zipCode:30367,
            contactPerson: "Fiser Contact Person",
            contactPhoneNumber: "770-895-9483",
            contactEmail: "fiserv@fiserv.com"
        },
        {
            // client_id: generated by sequelize assumed 1
            company_id: 1,
            name: "Microsoft",
            addrLine1: "Microsoft Address Line 1",
            addrLine2: "Microsoft Address Line 2",
            city:"Atlanta",
            state:"Georgia",
            zipCode:30350,
            contactPerson: "Microsoft Contact Person",
            contactPhoneNumber: "404-788-6692",
            contactEmail: "microsoft@microsoft.com"
        },
       
    ];

    // create function that bulk creates data using the array I created
    const seedClient = () => Client.bulkCreate(ClientData);

/* -------------------------------------------------------------------------- */
/*                              Export the Module                             */
/* -------------------------------------------------------------------------- */

    module.exports = seedClient; 