/* -------------------------------------------------------------------------- */
/*                             Import Dependencies                            */
/* -------------------------------------------------------------------------- */

    // const {Comment} = require('../models')

/* -------------------------------------------------------------------------- */
/*                            Define Data to Inject                           */
/* -------------------------------------------------------------------------- */
    // Define array of data to seed
    const commentData = [
        {
            // comment_id: generated by sequelize assumed 1
            ticket_id: 1,
            user_id: 1,
            comment: "This is a comment on ticket 1",
            date_created:"", // confirm format
            date_modified:"", // confirm format
        },
        {
            // comment_id: generated by sequelize assumed 2
            ticket_id: 2,
            user_id: 2,
            comment: "This is a comment on ticket 2",
            date_created:"", // confirm format
            date_modified:"", // confirm format
        },
        {
            // comment_id: generated by sequelize assumed 3
            ticket_id: 3,
            user_id: 3,
            comment: "This is a comment on ticket 3",
            date_created:"", // confirm format
            date_modified:"", // confirm format
        }
    ];

    // create function that bulk creates data using the array I created
    const seedComment = () => Ticket.bulkCreate(commentData);

/* -------------------------------------------------------------------------- */
/*                              Export the Module                             */
/* -------------------------------------------------------------------------- */

    module.exports = seedComment;  