/* -------------------------------------------------------------------------- */
/*                             Import Dependencies                            */
/* -------------------------------------------------------------------------- */

    const {Company} = require('../models');

/* -------------------------------------------------------------------------- */
/*                            Define Data to Inject                           */
/* -------------------------------------------------------------------------- */
    // Define array of data to seed
    const companyData = [
        {
            // company_id: generated by sequelize assumed 1
            companyName: 'OurSupportCompany',
        },
        {
            // company_id: generated by sequelize assumed 2
            companyName: 'AnotherSupportCompany',
        },
       
    ];

    // create function that bulk creates data using the array I created
    const seedCompany = () => Company.bulkCreate(companyData);

/* -------------------------------------------------------------------------- */
/*                              Export the Module                             */
/* -------------------------------------------------------------------------- */

    module.exports = seedCompany;  