/* -------------------------------------------------------------------------- */
/*                             Import Dependencies                            */
/* -------------------------------------------------------------------------- */

    const {Org} = require('../models');

/* -------------------------------------------------------------------------- */
/*                            Define Data to Inject                           */
/* -------------------------------------------------------------------------- */
    // Define array of data to seed
    const orgData = [
        {
            // company_id: generated by sequelize assumed 1
            name: 'Our Support Company',
        },
        {
            // company_id: generated by sequelize assumed 2
            name: 'Another Support Company',
        },
       
    ];

    // create function that bulk creates data using the array I created
    const seedOrg = () => Org.bulkCreate(orgData);

/* -------------------------------------------------------------------------- */
/*                              Export the Module                             */
/* -------------------------------------------------------------------------- */

    module.exports = seedOrg;  