/* -------------------------------------------------------------------------- */
/*                             Import Dependencies                            */
/* -------------------------------------------------------------------------- */

    const {Team} = require('../models')

/* -------------------------------------------------------------------------- */
/*                            Define Data to Inject                           */
/* -------------------------------------------------------------------------- */
    // Define array of data to seed
    const teamData = [
        {
            // team_id: generated by sequelize assumed 1
            company_id: 1,
            user_id: 1,
            name:'team one'
        },
        {
            // team_id: generated by sequelize assumed 2
            company_id: 1,
            user_id: 2,
            name:'team two'
        },
        {
            // team_id: generated by sequelize assumed 3
            company_id: 1,
            user_id: 3,
            name:'team three'
        },
      
    ];

    // create function that bulk creates data using the array I created
    const seedTeam = () => Team.bulkCreate(teamData);

/* -------------------------------------------------------------------------- */
/*                              Export the Module                             */
/* -------------------------------------------------------------------------- */

    module.exports = seedTeam;  