/* -------------------------------------------------------------------------- */
/*                             Import Dependencies                            */
/* -------------------------------------------------------------------------- */

    const {Ticket} = require('../models');

/* -------------------------------------------------------------------------- */
/*                            Define Data to Inject                           */
/* -------------------------------------------------------------------------- */
    // Define array of data to seed
    const ticketData = [
        {
            // ticket_id: generated by sequelize assumed 1
            company_id: 1,
            client_id: 1,
            team_id: 1,
            user_id: 1,
            status: "Open", // confirm optoins
            priority: "High", // Confirm options
            dateDue:"", // confirm format
            title:"ticket 1",
            description: "this is a ticket 1 descriptoin",
            user_id_reported_by:"", // confirm how to show this v user id who owns above
            date_created:"", // confirm format
            date_closed:"", // confirm format
            points: 4
        },
        {
            // ticket_id: generated by sequelize assumed 2
            company_id: 1,
            client_id: 2,
            team_id: 1,
            user_id: 2,
            status: "Open", // confirm optoins
            priority: "Medium", // confirm optoins
            dateDue:"", // confirm format
            title:"ticket 2",
            description: "this is a ticket 2 descriptoin",
            user_id_reported_by:"", // confirm how to show this v user id who owns above
            date_created:"", // confirm format
            date_closed:"", // confirm format
            points: 10
        },
        {
            // ticket_id: generated by sequelize assumed 3
            company_id: 1,
            client_id: 3,
            team_id: 1,
            user_id: 3,
            status: "Open", // confirm optoins
            priority: "Low", // confirm optoins
            dateDue:"", // confirm format
            title:"ticket 3",
            description: "this is a ticket 3 descriptoin",
            user_id_reported_by:"", // confirm how to show this v user id who owns above
            date_created:"", // confirm format
            date_closed:"", // confirm format
            points: 8
        }
    ];

    // create function that bulk creates data using the array I created
    const seedTicket = () => Ticket.bulkCreate(ticketData);

/* -------------------------------------------------------------------------- */
/*                              Export the Module                             */
/* -------------------------------------------------------------------------- */

    module.exports = seedTicket;  