/* -------------------------------------------------------------------------- */
/*                             Import Dependencies                            */
/* -------------------------------------------------------------------------- */

const { User } = require('../models');

/* -------------------------------------------------------------------------- */
/*                            Define Data to Inject                           */
/* -------------------------------------------------------------------------- */
// Define array of data to seed
const userData = [
    {
        // user_id: generated by sequelize assumed 1
        org_id: 1,
        client_id: null,  // should we have this for a user that is an employee, not a submitter of issues?
        first_name: "Ryan",
        last_name: "Johnson",
        role: 0,
        is_manager: false,
        password: 'pass1234',
        phone_number: '313-355-5881',
        email: 'admin@email.com',
        team_id: null,
        profile_icon: ""
    },
    {
        // user_id: generated by sequelize assumed 2
        org_id: 1,
        client_id: null, // should we have this for a user that is an employee, not a submitter of issues?
        first_name: "John",
        last_name: "Bell",
        role: 1,
        is_manager: true,
        password: 'pass1234',
        phone_number: '404-955-3455',
        email: 'manager@email.com',
        team_id: 1,
        profile_icon: ""
    },
    {
        // user_id: generated by sequelize assumed 3
        org_id: 1,
        client_id: null, // should we have this for a user that is an employee, not a submitter of issues?
        first_name: "Brandon",
        last_name: "Haley",
        role: 1,
        is_manager: false,
        password: 'pass1234',
        phone_number: '404-245-6911',
        email: 'employee@email.com',
        team_id: 1,
        profile_icon: ""
    },
    {
        // user_id: generated by sequelize assumed 4
        org_id: 1,
        client_id: 1, // should we have this for a user that is an employee, not a submitter of issues?
        first_name: "Alan",
        last_name: "Smith",
        role: 2,
        is_manager: false,
        password: 'pass1234',
        phone_number: '404-245-6912',
        email: 'client@email.com',
        team_id: null,
        profile_icon: ""
    },


];

// create function that bulk creates data using the array I created
const seedUser = () => User.bulkCreate(userData);

/* -------------------------------------------------------------------------- */
/*                              Export the Module                             */
/* -------------------------------------------------------------------------- */

module.exports = seedUser;