/* -------------------------------------------------------------------------- */
/*                             Import Dependencies                            */
/* -------------------------------------------------------------------------- */

    const {User} = require('../models');

/* -------------------------------------------------------------------------- */
/*                            Define Data to Inject                           */
/* -------------------------------------------------------------------------- */
    // Define array of data to seed
    const userData = [
        {
            // user_id: generated by sequelize assumed 1
            company_id: 1,
            client_id: 1, // should we have this for a user that is an employee, not a submitter of issues?
            firstName: "Ryan",
            lastName: "Johnson",
            role:"Admin",
            isManager: true,
            password: 'password1',
            phoneNumber: '313-355-5881',
            email:'theycallmethejman@hotmail.com',
            team_id: 1,
            profileIcon:""
        },
        {
            // user_id: generated by sequelize assumed 2
            company_id: 1,
            client_id: 2, // should we have this for a user that is an employee, not a submitter of issues?
            firstName: "John",
            lastName: "Bell",
            role:"Employee",
            isManager: false,
            password: 'password2',
            phoneNumber: '404-955-3455',
            email:'pappaJohn@bellsouth.net',
            team_id: 2,
            profileIcon:""
        },
        {
            // user_id: generated by sequelize assumed 3
            company_id: 1,
            client_id: 3, // should we have this for a user that is an employee, not a submitter of issues?
            firstName: "Brandon",
            lastName: "Haley",
            role:"Employee",
            isManager: false,
            password: 'password3',
            phoneNumber: '404-245-6911',
            email:'iBstuntin@gmail.com',
            team_id: 3,
            profileIcon:""
        },
      
      
    ];

    // create function that bulk creates data using the array I created
    const seedUser = () => User.bulkCreate(userData);

/* -------------------------------------------------------------------------- */
/*                              Export the Module                             */
/* -------------------------------------------------------------------------- */

    module.exports = seedUser;  